Task 7
Wgheth/Waled_ncnews pull request #6
Opened 2023-01-18 10:37 UTC by Wgheth

2023-01-18 11:49 UTC, NRMSMITH requested changes
Req changes: a few tests need to be added (see comments!) 😄

2023-01-18 11:49 UTC, NRMSMITH commented on __tests__/app.test.js
Add tests for the following scenario:

the username does not exist
the required fields (username / body) are not present
201: the body sent has extra properties, i.e.: {username: 'icellusedkars', body: 'comment', hour: '12'} (hour should be ignored!)

2023-01-18 11:49 UTC, NRMSMITH commented on controllers/news.controller.js
> +      })
what you send back should be on an appropriate key, such as 'comment'.

2023-01-19 10:56 UTC, mezzDavies requested changes
Hi Waled there is still a lot of things to think about - especially with your testing. My comments should spell the way 👍 

I have also left some suggestions for tidying up test descriptions 😄 

Please have a look and resubmit.

2023-01-19 10:56 UTC, mezzDavies commented on __tests__/app.test.js
> +  test('Returns Error with 404 if the article id is invalid', () => {
You need to update the test description to match the assertion 404 v 400.

2023-01-19 10:56 UTC, mezzDavies commented on __tests__/app.test.js
> +   .get("/api/articles/article/commentS")
You could also make the test more explicit by putting something like `.get("/api/articles/invalid_article_id/comment")` . No biggie - just helpful.

2023-01-19 10:56 UTC, mezzDavies commented on __tests__/app.test.js
> +  describe("POST /api/articles/:article_id/comments", () => {
We don't need the array to be returned here just the created comment object (on a key of comment or similar). Arrays are for more than one item and we are only returning one item - the comment. We can make this happen by returning just the comment object from the Model to the Controller.

2023-01-19 10:56 UTC, mezzDavies commented on models/news.model.js
> +      [req.body[0]["body"], req.body[0]["username"], article_id, 0]
All this (taking data from the request) should be handled in the controller.

2023-01-19 10:56 UTC, mezzDavies commented on __tests__/app.test.js
> +      const postartecle = [
You need to send the comment that is to be added as an object not in an array here and deal with it as per my other comments (in the controller).

2023-01-19 10:56 UTC, mezzDavies commented on __tests__/app.test.js
> +    test("It returns status code 201 and array with an object that have an updated body and author properties", () => {
The test description needs to match the assertion made. 👍

2023-01-19 10:56 UTC, mezzDavies commented on __tests__/app.test.js
>    describe("/api/articles/:article_id/comments", () => {
Think about what exactly this describe block contains  - these are all GET requests

2023-01-19 10:56 UTC, mezzDavies commented on models/news.model.js
> +    return result.rows;
You can take the comment off rows and return it back to the controller here, as per my other comments.

2023-01-19 10:56 UTC, mezzDavies commented on __tests__/app.test.js
> +  });
You still need to test for: 

- if the username and or body are not present on the request 
- if the body has extra properties - they are ignored
- a request is made with valid but non existent article id
- the body is missing the required properties

2023-01-20 10:04 UTC, closed without merging